import '../styles/globals.css'
import { store } from '../store/store'
import { Provider } from "react-redux"
import React from 'react'

import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  return(
    <Provider store={store}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </Provider>
  )
}

export default MyApp
